user:
  start_id: 0
  count: 100
  output_file: generated_data/users.csv
car_type:
  start_id: 0
  count: 20
  output_file: generated_data/car_types.csv
parking_station:
  start_id: 0
  count: 100
  output_file: generated_data/parking_station.csv
car:
  start_id: 0
  count: 100
  output_file: generated_data/cars.csv
  depends_on:
    - car_type
    - parking_station
